Repository c2c-project/prytaneum, pull requests merged in 2022-12, with the labels that each got.

#259 Implement client side message validation
  app/client/src/features/events/LiveFeedback/LiveFeedbackForm.tsx
  app/client/src/features/events/LiveFeedback/SubmitLiveFeedback.tsx
  app/client/src/features/events/Questions/AskQuestion/AskQuestion.tsx
  app/client/src/features/events/Questions/QuestionForm/QuestionForm.tsx
  app/client/src/utils/index.ts
  app/client/src/utils/rules.ts
Labels: ready-for-review

#376 Question position string update
  app/client/schema.graphql
  app/client/src/__generated__/DeleteButtonFragment.graphql.ts
  app/client/src/__generated__/DequeueQuestionButtonMutation.graphql.ts
  app/client/src/__generated__/EnqueueQuestionButtonFragment.graphql.ts
  app/client/src/__generated__/EnqueueQuestionButtonMutation.graphql.ts
  app/client/src/__generated__/NextQuestionButtonMutation.graphql.ts
  app/client/src/__generated__/PreviousQuestionButtonMutation.graphql.ts
  app/client/src/__generated__/QuestionCarouselFragment.graphql.ts
  app/client/src/__generated__/QuestionQueueMutation.graphql.ts
  app/client/src/__generated__/QueueButtonFragment.graphql.ts
  app/client/src/__generated__/useEnqueuedPushSubscription.graphql.ts
  app/client/src/__generated__/useEnqueuedUnshiftSubscription.graphql.ts
  app/client/src/__generated__/useQuestionCreatedSubscription.graphql.ts
  app/client/src/__generated__/useQuestionDeletedSubscription.graphql.ts
  app/client/src/__generated__/useQuestionListFragment.graphql.ts
  app/client/src/__generated__/useQuestionQueueFragment.graphql.ts
  app/client/src/__generated__/useQuestionUpdatedSubscription.graphql.ts
  app/client/src/__generated__/useRecordPushSubscription.graphql.ts
  app/client/src/__generated__/useRecordUnshiftSubscription.graphql.ts
  app/client/src/features/events/Moderation/ManageQuestions/CurrentQuestionCard.tsx
  app/client/src/features/events/Moderation/ManageQuestions/QuestionQueue.tsx
  app/client/src/features/events/Questions/QuestionActions/DeleteButton.tsx
  app/client/src/features/events/Questions/QuestionActions/QueueButton.tsx
  app/client/src/features/events/Questions/QuestionCarousel/QuestionCarousel.tsx
  app/client/src/graphql-types.ts
  app/server/prisma/migrations/20221202085215_question_position_and_current_question_updated_to_string/migration.sql
  app/server/prisma/schema.prisma
  app/server/src/features/events/methods.ts
  app/server/src/features/events/moderation/methods.ts
  app/server/src/features/events/moderation/schema.graphql
  app/server/src/features/events/questions/methods.ts
  app/server/src/features/events/questions/schema.graphql
  app/server/src/features/events/resolvers.ts
  app/server/src/features/events/schema.graphql
  app/server/src/graphql-types.ts
Labels: bug-fix

#136 Fixes for the frontend
  app/client/src/components/CopyText/CopyText.tsx
  app/client/src/components/SettingsMenu/SettingsMenu.tsx
  app/client/src/components/index.ts
  app/client/src/core/SnackContext.tsx
  app/client/src/core/useForm.ts
  app/client/src/core/useSnack.ts
  app/client/src/features/accounts/LoginForm.tsx
  app/client/src/features/accounts/RegisterForm.tsx
  app/client/src/features/accounts/UserSettings/components.tsx
  app/client/src/features/events/CreateEvent.tsx
  app/client/src/features/events/DeleteEvent.tsx
  app/client/src/features/events/EventForm.tsx
  app/client/src/features/events/EventSettings/EventDetails.tsx
  app/client/src/features/events/EventSettings/EventSettings.tsx
  app/client/src/features/events/Invites/CreateInvite.tsx
  app/client/src/features/events/Invites/InviteEventSettings.tsx
  app/client/src/features/events/Invites/InviteForm.tsx
  app/client/src/features/events/LiveFeedback/SubmitLiveFeedback.tsx
  app/client/src/features/events/LiveFeedback/useLiveFeedbackPrompt.tsx
  app/client/src/features/events/Moderation/CreateModerator.tsx
  app/client/src/features/events/Moderation/DeleteModerator.tsx
  app/client/src/features/events/Moderation/ModeratorEventSettings.tsx
  app/client/src/features/events/Moderation/ModeratorForm.tsx
  app/client/src/features/events/Speakers/SpeakerForm.tsx
  app/client/src/features/events/UpdateEvent.tsx
  app/client/src/features/events/Videos/VideoForm.tsx
  app/client/src/features/organizations/CreateOrg.tsx
  app/client/src/features/organizations/MemberForm.tsx
  app/client/src/features/organizations/OrgEventList.tsx
  app/client/src/features/organizations/OrgForm.tsx
  app/client/src/features/organizations/OrgMemberList.tsx
  app/client/src/layout/Footer/Footer.tsx
Labels: UI/UX, bug-fix
